### ISSUE TITLE
Post images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#5] opened 2021-03-02 05:50 UTC
I notice that the images you use for news often have text on them. But the text will often be cropped.
Both in the [list view](https://hp-colombian-biodiversity.gbif-staging.org/news/) and on [individual pages](https://hp-colombian-biodiversity.gbif-staging.org/post/2020/convocatoria-bid-caribe-2020/)

The [post layout](https://hp-base-theme.gbif-staging.org/layout/post) - that is used for news - have a fixed default image ratio. And the [list of news](https://hp-colombian-biodiversity.gbif-staging.org/news/) have a slightly other. That makes it difficult to use text on the images, or at least it have to be carefully placed.

I can see these options to improve it
* remove the text - in many cases it just [repeats the headline](https://hp-colombian-biodiversity.gbif-staging.org/post/2021/jovenes-investigadores-2021/)
* change the image ratio on the individual posts. E.g. `ratio: 100` (Height in percentage relative to width)
* crop or create the images so that you know they will work in the used ratios

The difference in aspect ratio between [the cards](https://hp-colombian-biodiversity.gbif-staging.org/news/) and the [individual page](https://hp-colombian-biodiversity.gbif-staging.org/post/2020/convocatoria-bid-caribe-2020/) makes it extra difficult to select an image with text. I will think about what I can do at theme level to make that use case easier.

And to make it more difficult the images might be cropped differently on different device sizes.

<img width="375" alt="Screenshot 2021-03-02 at 06 45 54" src="https://user-images.githubusercontent.com/6759267/109604017-187f4d80-7b23-11eb-8115-0b2d146599fa.png">

<img width="757" alt="Screenshot 2021-03-02 at 06 45 30" src="https://user-images.githubusercontent.com/6759267/109604010-14ebc680-7b23-11eb-892e-1f5c55fe2bd3.png">

**Comment by MortenHofft** [comment] 2021-03-02 09:44
I've added the option to use another image for thumbnails on cards, that should give you more control over how the news cards look.

Just add `thumbnail: /assets/images/your-image-path` to the post to overwrite it
https://hp-base-theme.gbif-staging.org/layout/post

**Comment by verovanporras** [comment] 2021-03-04 16:58
You are right, what happens is that we are transferring the content that we had in our page [sibcolombia.net](https://sibcolombia.net/actualidad/blog/). We have not yet modified the size of the images, I hope that when we have all the notes up, I can dedicate myself to the images.

**Comment by camiplata** [comment] 2022-01-08 22:21
We will start using the thumbnail on 2022 @aduarte-sib @RicardoOrtizG, but for the olss posts the issue is closed as we wont make adjustments for those.

**Closed by camiplata** 2022-01-08 22:21 UTC
Labels: enhancement
